### ISSUE TITLE
Confusion with translate_IG.py

### ISSUE THREAD

**Issue by Laughableomputers** [davkovacs/MTExplainer#4]
Could you please give a detailed example of using translate_IG.py, it is difficult for beginners to understand the required files such as -baseline, -tgt2, etc
Thanks.

**Comment by davkovacs** [comment]
I think the instructions in the README are fairly clear together with the paper. I am sorry, but this is a very old projects, and I don't actively support it any more. Baseline should be where the integrateg gradients are calculated from, and tgt2 is a second target if given. See the paper for examples for what these can be.
